services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WebentwicklerAt\Loginlimit\:
        resource: '../Classes/*'

    WebentwicklerAt\Loginlimit\Command\CleanupCommand:
        tags:
            -   name: 'console.command'
                command: 'loginlimit:cleanup'
                schedulable: true
